/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * The RadiancePlugin registers a simple Gradle task named 'greeting' that prints a greeting message.
 */
public class RadiancePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'org.example.greeting'"));
        });
    }
}
